feat: add sonar properties

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -37,3 +37,16 @@ jobs:
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+      - name: Verificar status do Quality Gate
+        run: |
+          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=ca-ayumi_fast-food-order-service" \
+          | jq -r '.projectStatus.status')
+          
+          if [[ "$STATUS" != "OK" ]]; then
+            echo "❌ SonarCloud Quality Gate failed. Coverage < 80%."
+            exit 1
+          else
+            echo "✅ SonarCloud Quality Gate passed. Coverage >= 80%."
+          fi
